### ISSUE TITLE
Refactor Codebase with best practice [ Deadline: June 10th ]

### ISSUE THREAD

**Issue by miclovich** [steviebuckets/podfeed#4]
We'll work through refactoring some of the code, improving the names of the variables or reducing any clutter in the code.

**Comment by steviebuckets** [comment]
Sounds good. Just cleaned up some stuff and removed old comments.

**Comment by miclovich** [comment]
you are on track.. the `mapDispatchToProps` was replaced with a shorthand, another thing that could do with a refactor is including callbacks to your `axios` requests/action creators.
